return {
  id = "sys-http",
  name = "sys-http smoke",
  description = "Pruebas manuales del servidor educativo sys-http.",
  variables = {
    base_url = "http://localhost:5050",
  },
  folders = {
    { id = "static", name = "Static" },
    { id = "database", name = "Database" },
  },
  requests = {
    {
      id = "root",
      folder = "static",
      name = "GET /",
      protocol = "rest",
      method = "GET",
      url = "{{base_url}}/",
      headers = {},
    },
    {
      id = "index",
      folder = "static",
      name = "GET /index.html",
      protocol = "rest",
      method = "GET",
      url = "{{base_url}}/index.html",
      headers = {},
    },
    {
      id = "missing",
      folder = "static",
      name = "GET missing file",
      protocol = "rest",
      method = "GET",
      url = "{{base_url}}/no-existe",
      headers = {},
    },
    {
      id = "traversal",
      folder = "static",
      name = "GET traversal",
      protocol = "rest",
      method = "GET",
      url = "{{base_url}}/../etc/passwd",
      headers = {},
    },
    {
      id = "database-set",
      folder = "database",
      name = "POST /database",
      protocol = "rest",
      method = "POST",
      url = "{{base_url}}/database",
      headers = {
        { name = "Content-Type", value = "application/json" },
      },
      body = {
        type = "json",
        content = '{"key":"smoke","value":"ok"}',
      },
    },
    {
      id = "database-get",
      folder = "database",
      name = "GET /database/smoke",
      protocol = "rest",
      method = "GET",
      url = "{{base_url}}/database/smoke",
      headers = {},
    },
    {
      id = "database-invalid",
      folder = "database",
      name = "POST /database without key",
      protocol = "rest",
      method = "POST",
      url = "{{base_url}}/database",
      headers = {
        { name = "Content-Type", value = "application/json" },
      },
      body = {
        type = "json",
        content = '{"value":"missing-key"}',
      },
    },
  },
}
